# Makefile for programming challenge 21
#
# CSCI 21, Spring 2014
#
# Programmer: Talea Mitchell
#

FLAGS = -Wall -Wextra -Werror -pedantic

# Target for programming challenge 21
# date completed: 4-21-2014
pc21: pc21.cpp box.h
	g++ $(FLAGS) -o pc21 pc21.cpp